### ISSUE TITLE
prefix sum

### ISSUE THREAD

**Issue by jinz2014** [intel/cm-compiler#10]
I ran the prefix sum test with the following result on a Gen8 GPU. I assume the first and last test cases are too small and too big in terms of the number of rows in a column. Can you please explain the issues ?   In addition, is it recommended to measure the GPU time from creating a cm device ?  Are you aware of any open-source OpenCL applications that implement prefix sum ?  

Thank you

-------- 

./Prefix 8
Prefix => FAILED

./Prefix 16
Prefix => PASSED

./Prefix 24
CM-ERROR: Internal Error Prefix.cpp 191

**Comment by cmc-rep** [comment]
I do not have a Gen8 machine. I tried it on my gen9 machine. 8 also failed. The working range for me is from 10 to 27.  After 27, I suspect we may have a memory allocation problem or a thread-space size limitation issue for this example.  Right now I do not know why it does not work for 2^8 or 2^9 items. I will try to find out

**Comment by jinz2014** [comment]
I believe it is a memory allocation problem for 27. Thanks for looking into the issue and update.

**Comment by jinz2014** [comment]
Could you please explain the cause of the issue ?  Thanks

**Comment by cmc-rep** [comment]
which part do you need explanation? >27 not working or <10 not working

**Comment by jinz2014** [comment]
Both if you don't mind

**Comment by cmc-rep** [comment]
Sorry, I do not have time to look into this carefully. 
For > 27, looks like that we may have a memory allocation problem.
For < 10, looks like some incomplete code, we expect to do it on CPU, but we do not have that code
see the following comment and condition
  // For small input size, we only have a small number of threads
  // we don't call kernel to compute prefix sum. intead of,
  // CPU simply performs the job
  if (size >= 1024) {
