### ISSUE TITLE
Support Mac OS

### ISSUE THREAD

**Issue by KnowingNothing** [intel/cm-compiler#15]
Is there any support for Mac OS? I'd like to use the compiler on Macbook. Could anyone provide some guidance about how to set up this compiler and runtime?

**Comment by cmc-rep** [comment]
We do not support Mac OS. However, I expect it is not very hard to build the compiler on MacOS.
Sorry, we do not provide runtime on Mac OS.

**Comment by cmc-rep** [comment]
No fix for this, so close the issue
