### ISSUE TITLE
CopyPipeline incorrect Threshold value assignment

### ISSUE THREAD

**Issue by sapoluri** [intel/cm-compiler#16]
In file test/external_contribution/CopyPipeline6/Threshold_ProduceEdgeK/Threshold_ProduceEdgeK.cpp

Instead assigning values to the class variables, you allocate it to local variables:
short m_thresholdK = 96;
short m_thresholdMaxFilter = 130;

At runtime, when passing values to kernel, instead of above values, zeroes are passed since the class variables were never set.

Please fix it.

**Comment by cmc-rep** [comment]
Thanks. We will fix this.
