### ISSUE TITLE
GenX_IR doesn't exist

### ISSUE THREAD

**Issue by jinz2014** [intel/cm-compiler#20]
I built the compiler using the script, then I got the following error when building an example using the option "-Qxcm_jit_target=xxx".  
clang-6.0: error: unable to execute command: Executable "/home/cc/cm-compiler/build.64.linux/bin/GenX_IR" doesn't exist!

However, I found the file in the CM development package. Could you please clarify the installation process? For example, do users need to replace the 'cmc' binary in the package with the 'cm' binary built from source ?

**Comment by cmc-rep** [comment]
GenX_IR is not built from cm-compiler source. It is built from IGC source github.com/intel/intel-graphics-compiler.
Therefore you could either replace cmc in the CM development package, or copy GenX_IR into your /home/cc/cm-compiler/build.64.linux/bin/

**Comment by jinz2014** [comment]
Could you please tell the differences between the cmc in the development package and the cmc built from source ?
For example, I may just build programs using the cmc in the development package without building it from source.

Thanks

**Comment by cmc-rep** [comment]
Usually there is no difference.  However, we may update the source with bug fixes etc, then cmc in the development package may lag behind.

**Comment by jinz2014** [comment]
You may also update the cmc in the development package.  Thanks.

**Comment by cmc-rep** [comment]
The release package needs to go through a testing process. The open-source code also enables users to extend/customize the language if necessary.
