### ISSUE TITLE
question about linear walker

### ISSUE THREAD

**Issue by jinz2014** [intel/cm-compiler#22]
As shown in the following codes, the 'width' is the width of an image.  Each pixel has 24 bits. Since the surface format requires 32 bits per pixel, then
  surface width = image width * 4 / 3
Is that right ?

In addition, is there any reference to the design of your walker kernels ?  Naively, each thread computes the average sum of 9 pixel values of an input image, stores the average into an intermediate buffer, and finally copy the intermediate buffer from a GPU to a host. The number of threads equal the number of pixels in an output image. 

Thanks

  
// Creates input surface with given width and height in pixels and format.
  // Sets surface format as CM_SURFACE_FORMAT_A8R8G8B8. For this format, each
  // pixel occupies 32 bits.
  // The input image is RGB format with 24 bits per pixel, and the surface
  // format is A8R8G8B8 with 32 bits per pixel. Therefore, the surface width
  // is (width*3/4) in pixels.
  CmSurface2D *input_surface = nullptr;
  cm_result_check(device->CreateSurface2D(width*3/4,
                                          height,
                                          CM_SURFACE_FORMAT_A8R8G8B8,
                                          input_surface));

**Comment by cmc-rep** [comment]
Every thread computes and outputs a 6x8 pixel-block.  therefore the workspace setting is [(width/8),  (height)/6]

**Comment by cmc-rep** [comment]
Yes, the surface settting looks a bit strange. This is because CM does not have a surface format of R8G8B8. However the input image is indeed 3 channels and 24 bits per pixel.  To use the surface-format A8R8G8B8, we have to do
surface-width = image-width * 3 / 4;

**Comment by jinz2014** [comment]
image-width = 24 bits, then 'image-width * 3 / 4' = 18 bits.  Is it right ?

**Comment by cmc-rep** [comment]
image-width is 800 pixels.  therefore surface-width looks like 600 pixels

**Comment by jinz2014** [comment]
I understand that in your kernel each thread computes a 6x8 pixel-block, but your kernel seems to add up these 6x8 pixel-blocks. Is my understanding right ?
For a naive kernel, each thread just computes one pixel (which is the average of the neighboring 9 pixel) in an output image. So I don't understand your pixel-block algorithm. That is why I asked if there are some reference to your algorithm.

**Comment by cmc-rep** [comment]
Sorry, no reference other than the comments in the code. Yes, the kernel adds up these 6x8 pixel-blocks. 
As you may have seen there are 9 different 6x8 pixel-blocks, which have different upper-left corner offsets
(0, 0), (0, 3), (0, 6), (3, 0), (3, 3), (3, 6) ... etc.
By adding these blocks, every output pixel is the sum of a 3x3 input pixels

**Comment by jinz2014** [comment]
Thank you for explaining the implementation.
