### ISSUE TITLE
How I can install the CM compiler which I have built to the desired location?

### ISSUE THREAD

**Issue by dvrogozh** [intel/cm-compiler#3]
I do not see a way to install the compiler which I have built to the desired location. Is there a way?

I would like to be able to freely configure the usual Linux range of installation directories, the major things to support are --prefix and --libdir. If you are using CMake options are described here: https://cmake.org/cmake/help/v3.6/module/GNUInstallDirs.html

Mind please, that absence of clear installation path will block adoptions of the compiler in the Linux distributions.

**Comment by dvrogozh** [comment]
@chivakker : FYI

**Comment by dvrogozh** [comment]
Which other projects make it complete product? Are you talking about https://github.com/intel/media-driver?

If so, then cm-compiler is most definitely a standalone _package_. Other packages will depend on it. For example, mediasdk will depend on it to build CM shaders (see https://github.com/Intel-Media-SDK/MediaSDK/pull/922 - we now look for the command lines to build these sources). If media-driver will later on publish their CM shaders, then media-driver will depend on cm-compiler as well.

Moreover, the job of cm-compiler per my opinion is just to build shaders. It may not even depend on the driver/runtime - application which uses these shaders will need to depend on them.

**Comment by cmc-rep** [comment]
I am talking about this one: https://01.org/c-for-media-development-package.
Let me try to understand your request better so I can talk to people who put this package together.
Where do you want to install cmc?  Where do you want to install the header files from support/include?
Is it necessary to put these things under somewhere like "/usr" in order for you to build media kernels?

**Comment by dvrogozh** [comment]
I am anticipating to have cmc available as a standard package on Linux distributions. Ubuntu, Fedora, Clear Linux, etc. This issue will block this effort. Installation will eventually be in /usr. I definitely would like to review list of installation artifacts.

**Comment by dvrogozh** [comment]
I see the following tree after installing via '-i' option:
```
# tree /home/dvrogozh/git/github/cmc/
/home/dvrogozh/git/github/cmc/
├── bin
│   └── cmc
└── include
    └── cm
        ├── cm_atomic.h
        ├── cm_common.h
        ├── cm_dataport.h
        ├── cm_gateway.h
        ├── cm.h
        ├── cm_internal.h
        ├── cm_linear.h
        ├── cm_printf.h
        ├── cm_sampler.h
        ├── cm_send.h
        ├── cm_svm.h
        ├── cm_target.h
        ├── cmtl.h
        ├── cm_traits.h
        ├── cm_util.h
        ├── cm_vme.h
        ├── gen10_vme.h
        ├── gen11_vme.h
        ├── gen7_5_vme.h
        ├── gen8_vme.h
        └── gen9_vme.h

3 directories, 22 files
```

This looks good to me. However, I need to manually specify -isystem /path/to/cm/*.h headers in order to be able to build shaders. I believe that compiler installation should take care of this. I.e. I should not specify -isystem, this should be programmed inside cmc binary.

For example, consider compiling something trivial via gcc, clang and cmc:
`main() { return 0; }`
You will get the following via `<compiler> -v file.c`:
```
# for gcc:
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include
 /usr/local/include
 /usr/include

# for clang:
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /opt/rh/llvm-toolset-7/root/usr/lib64/clang/5.0.1/include
 /usr/include

# for cmc:
#include "..." search starts here:
```

So, as you can see default search directories list is empty for cmc. Can this be changed and correct path to cm/*.h programmed into cmc binary?

**Comment by cmc-rep** [comment]
I have added a default include search path. support cmc is from .../bin/cmc, then it would search ../include for cm headers
