### ISSUE TITLE
Possible problems with EU-deficient GPUs

### ISSUE THREAD

**Issue by TakedaHiromasa** [intel/cm-compiler#42]
Hello,
I am enjoying benchmarking C_for_Metal to see how well it performs.
C_for_Metal is a dedicated language to take full advantage of Intel GPUs.
However, I have found that there is a big problem in getting the full performance out of Intel GPUs.

# There are GPUs with inconsistent numbers of EUs
Take a look at the following exchange between Intel engineers and me.
https://community.intel.com/t5/OpenCL/The-EU-count-of-Iris-Plus-Graphics-655-is-wrong/m-p/1245411

Apparently, some Intel GPUs may have less EU than the catalog specs.
For example...
I'm using NUC8i3BEH.
The SoC of NUC8i3BEH is i3-8109U.
The internal GPU of the i3-8109U is "Iris Plus Graphics 655".
Many documents found on Intel show the "Iris Plus Graphics 655" as being 48EU.
However, in clinfo and C_for_Metal, it is displayed as 47EU.

# Possible C_for_Metal problems with EU-deficient GPUs
Let's look at my machine, which is listed as 48EU in the catalog, but is actually only 47EU.
First, of course, the number of hardware threads is displayed low.
This is only natural because one EU is missing.
```c++
unsigned int HWThreadCount = 0;
device->GetCaps(CAP_HW_THREAD_COUNT, 4, &HWThreadCount);
// output:
// HW thread count  : 329
```

The problem is thread groups.
In the CM language, thread groups appear to be assigned to SubSlices.
And the maximum amount of thread space in the group seems to depend on "Threads Per Subslice".
On my machine, "Threads Per Subslice" appears to be 49.
```c++
unsigned int ThreadsPerGroup = 0;
device->GetCaps(CAP_USER_DEFINED_THREAD_COUNT_PER_THREAD_GROUP, 4, &ThreadsPerGroup );
// output:
// Threads per group: 49
```
This is probably because there are only 7 EUs in slice0:SubSlice0. (7EU * 7 HW thread)
The low number of EUs for slice0:SubSlice0 can be confirmed from the driver debug information.
```bash
$ sudo cat /sys/kernel/debug/dri/0/i915_gpu_info
slice0: 3 subslice(s) (0x7):
    subslice0: 7 EUs (0xbf)
    subslice1: 8 EUs (0xff)
    subslice2: 8 EUs (0xff)
    subslice3: 0 EUs (0x0)
slice1: 3 subslice(s) (0x7):
    subslice0: 8 EUs (0xff)
    subslice1: 8 EUs (0xff)
    subslice2: 8 EUs (0xff)
    subslice3: 0 EUs (0x0)
slice2: 0 subslice(s) (0x0):
    subslice0: 0 EUs (0x0)
    subslice1: 0 EUs (0x0)
    subslice2: 0 EUs (0x0)
    subslice3: 0 EUs (0x0)
```

If you actually try to allocate more than 49 thread spaces with the `CreateThreadGroupSpace();` function in this environment, it will fail.
```c++
CreateThreadGroupSpace(49, 1, 1, 1, thread_group_space));
// Success!

CreateThreadGroupSpace(50, 1, 1, 1, thread_group_space));
// CM-ERROR: CM_INVALID_THREAD_GROUP_SPACE
```
In my opinion, this causes a huge performance degradation.
If the ThreadGroup indicates a SubSlice, then a failure of slice0:SubSlice0 will cause all SubSlices to use only 7EU.
Thus, a total of 5 EU is lost.
Intel engineers say that 1EU will only reduce the performance by 2%, but losing 5EU is a different story!

What I am wondering is how the CM language handles EU/Thread.
Isn't it possible to limit the functionality of all SubSlices if the EU of slice0:SubSlice0 is missing?
It looks like that to me.

What is your opinion on this issue?
Thanks.

**Comment by TakedaHiromasa** [comment]
Postscript.

My guess is that there is a problem even if you don't use thread groups.
(I don't have much information, so I can only speak from my imagination.)

When I inquire about "EU Per Subslice", it shows 7.
This is the same trend as "Threads Per Subslice" in the previous question.
```c++
CM_PLATFORM_INFO platform_info;
CapValueSize = sizeof(CM_PLATFORM_INFO);
device->GetCaps(CAP_PLATFORM_INFO, CapValueSize, &platform_info);
printf("EU Per Subslice  : %u\n", platform_info.numEUsPerSubSlice);
// EU Per Subslice  : 7
```

I do not see any function in CM to get the total number of EUs.
Therefore, it would be a big loss if the program is running with the following formula to get the total number of EUs and threads internally.
`[EU Per Subslice] * [Subslice num] = [Total EU]`
`[Threads Per Subslice] * [Subslice num] = [Total Threads]`
What algorithm does C_for_Metal use to check the total number of EU/threads?

**Comment by cmc-rep** [comment]
@TakedaHiromasa , good observation. I never looked into how many working EU actually there were on my machine.
That being said. I have two thought on this.
1) Typically, unless we need to use SLM within a work-group or to get better cache behavior, we typically set work-group size to 1.  For example, in histogram-256-slm example:
    ts_width = width / BLOCK_WIDTH;
    ts_height = height / BLOCK_HEIGHT;
    CmThreadGroupSpace *thread_space = nullptr;
    cm_result_check(device->CreateThreadGroupSpace(1, 1, ts_width, ts_height, thread_space));
But we launch a lot of thread to saturate the machine.  I guess the EU deficiency can be a problem when users try to launch the exact amount of threads on the target machine.

2) You could try to use VTune to see the overall EU utilization with your setting. You can compare them if you can also get hold of another machine which does NOT have deficient EU.

**Comment by TakedaHiromasa** [comment]
Thank.

I'll try to investigate using VTune for now.
I've never used VTune before, so it may take some time to investigate.
