### ISSUE TITLE
Compilations that use cm_svm.h fail because of missing parameter.

### ISSUE THREAD

**Issue by jasonsewall-intel** [intel/cm-compiler#7]
Is this a copy & paste bug?

https://github.com/intel/cm-compiler/blob/c49133b1f221a85b9f0f909273f9f15803f6793f/support/include/cm/cm_svm.h#L418

**Comment by cmc-rep** [comment]
Looks like redundant code, I will take a look.

BTW,  SVM right now is only supported on Windows due to OS and Runtime constraint. I have made the request for driver&runtime to support SVM on linux.
