### ISSUE TITLE
Intel C for Metal is nothing like C.

### ISSUE THREAD

**Issue by procedural** [intel/cm-compiler#71]
https://01.org/c-for-metal-development-package
> Host manages workloads through the Intel® C for Metal **Runtime and user mode media driver**.

Runtime and driver.

https://01.org/c-for-metal-development-package/blogs/huangli/2019/basic-host-programming
> **Just-In-Time**: **virtual ISA** to target ISA

JIT and IR.

This is not C.

C compiles offline to native hardware instructions that are sent to and executed on hardware without a user space driver.

**Comment by procedural** [comment]
This is OpenCL/CUDA with different host syntax and per-thread SIMD in kernels. C in the name has nothing to do with C.

**Comment by zjin-lcf** [comment]
the name of the language is CM; hope this is not confusing.

**Comment by procedural** [comment]
> the name of the language is CM; hope this is not confusing.

This CM acronym is referred to by Intel as C for Metal. The name is very confusing, I was expecting an actual C for metal, but saw another OpenCL-like for driver.
