### ISSUE TITLE
Broken build: ScalarOpts lib missing from build targets

### ISSUE THREAD

**Issue by voidcycles** [intel/cm-compiler#8]
The build is broken when building internal tools and libs such as libLTO, llvm-lto, llvm-spirv, etc due to a missing symbol:

<pre><font color="#8AE234"><b>Linking CXX executable ../../bin/llvm-spirv</b></font>
../../lib/libLLVMAnalysis.a(InstructionSimplify.cpp.o): In function `llvm::Value* SimplifyCall&lt;llvm::Use*&gt;(llvm::ImmutableCallSite, llvm::Value*, llvm::Use*, llvm::Use*, llvm::SimplifyQuery const&amp;, unsigned int) [clone .isra.579]&apos;:
InstructionSimplify.cpp:(.text._Z12SimplifyCallIPN4llvm3UseEEPNS0_5ValueENS0_17ImmutableCallSiteES4_T_S6_RKNS0_13SimplifyQueryEj.isra.579+0x1f1): undefined reference to `llvm::SimplifyGenXIntrinsic(unsigned int, llvm::Type*, llvm::Use*, llvm::Use*)&apos;</pre>

The missing symbol is due to a missing linkage for Transforms/Scalar/CMTrans/InstructionSimplifyGenX.cpp, which gets archived into the ScalarOpts static lib. 

It appears the link components list for all those build products is missing ScalarOpts from their corresponding CMakeLists.txt.

Adding ScalarOpts to the LLVM_LINK_COMPONENTS list should fix the problem.

**Comment by cmc-rep** [comment]
By default, we build opt and llc, I can add llvm-spirv. I will fix the build issue with llvm-spirv. Why would you need libLTO and llvm-lto?

**Comment by voidcycles** [comment]
Great thanks!  I was just pointing out that all internal targets are broken.  Not even the regression tests for clang work.
