### ISSUE TITLE
What compiler backend is used for CM_SDK?

### ISSUE THREAD

**Issue by Taiki-azrs** [intel/cm-compiler#83]
I used C for Metal when it was released in Development_Package. I recently found out that it has been updated to CM_SDK and was reading the documentation and was surprised to see that the contents have changed so much. I remember that an IR named GENX_IR was used before, what is used now?
Also, I cannot see the llvm related documents in the docs index.html because the links are disabled.

**Comment by vmustya** [comment]
@Taiki-azrs, currently the CM compiler is a clang frontend which generates SPIR-V handled by VC backend. VC backend is now a part of [Intel Graphics Compiler](https://github.com/intel/intel-graphics-compiler). 

We also do not support CM runtime anymore, so please migrate your workloads to [oneAPI Level Zero](https://spec.oneapi.io/level-zero/latest/index.html).
