### ISSUE TITLE
gpu_copy cannot execute on Linux 

### ISSUE THREAD

**Issue by dyang23** [intel/cm-compiler#85]
I am trying to run the sample code of gpu_copy() in Ubuntu, the hardware device is CML NUC, but it always stopped in function of 
    cm_result_check(device->CreateQueue(cmd_queue));

how can I solve this issue and run the gpu_copy successfully?

**Comment by vmustya** [comment]
CM RT is obsolete, and it's support will be dropped. So please migrate your workloads to either OpenCL or LevelZero runtime and new CM Compute SDK.

Development package is present here: https://01.org/c-for-metal-development-package

**Comment by dyang23** [comment]
Thanks
