### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by xipix** [intel/cm-compiler#86]
Hi, you have a broken link at the bottom of this page:

https://www.intel.com/content/www/us/en/developer/tools/open/c-for-metal-sdk/overview.html

Clicking on "Level Zero API" takes me to https://one-api.gitlab-pages.devtools.intel.com/level_zero/index.html but there's nothing there.

**Comment by ozhdikhin** [comment]
Hi, Thanks for spotting this. I'll fix the link.

**Comment by ozhdikhin** [comment]
Fixed now. The new link points to https://spec.oneapi.io/level-zero/latest/index.html.
