### ISSUE TITLE
Can not find the latest source code of the cm-compiler

### ISSUE THREAD

**Issue by YanfeiXu** [intel/cm-compiler#88]
Hi experts, I found the latest version of the intel-igc-cm Debian package is v1.0.206-736~22.04. And I am trying to compile it by this version from source code. However, I can't find the corresponding version or tag of source code in this repo.  Do you know how can I find the the v1.0.206 source code?  I am seeing the latest tag of this repo is v1.0.144 at Mar. 2022. Is this repo still alive or had migrated to other place? Thanks!

**Comment by ozhdikhin** [comment]
Hi YanfeiXu. This package corresponds to the following commit to cm-compiler in the manifest: [https://github.com/intel/cm-compiler/commit/9c7c90e24dd36300ec897a6358059cf6eccbc51b](https://github.com/intel/cm-compiler/commit/9c7c90e24dd36300ec897a6358059cf6eccbc51b).
