### ISSUE TITLE
question about libv, media_driver and cm-compiler

### ISSUE THREAD

**Issue by jinz2014** [intel/cm-compiler#9]
Hi Developers, 

I have troubling using CM compiler using the hello world example.

$ ./hello_world
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
CM-ERROR: CM_INVALID_LIBVA_INITIALIZE hello_world.cpp 49

However, when I installed media driver, iHD_drv_video is installed at /usr/local/lib64.
$ ls /usr/local/lib64/dri/
iHD_drv_video.so

/usr/local/lib/dri/i965_drv_video.so does not exist.  Should I rebuild libva or media driver or anything else ?

Thanks

**Comment by cmc-rep** [comment]
which media driver did you install? did you download our package from 01.org? Are you using Ubuntu? 
The following is the environment I have:
LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
LIBVA_DRIVER_NAME=iHD

**Comment by jinz2014** [comment]
I think the issue may be that I forgot to export the two environment variables in a terminal. It works now. 
In addition, I am not clear if we can make vISA of a (kernel) program human-readable. 

Thanks again.

**Comment by cmc-rep** [comment]
There is GenX_IR, you can use that to dump out vISA text, 

-dumpcommonisa
